# Generated by Django 4.2 on 2023-04-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_guest_juest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juest',
            old_name='mobile',
            new_name='mobil',
        ),
    ]
